### PR TITLE
[TASK] assure typo3temp/Cache is writeable

### PR DESCRIPTION
**Pull request by achimfritz**
cc @lars85

### CODE REVIEW

**Comment by ervaude** [comment]
:+1:

**Comment by ervaude** [comment]
Hmm. This will basically require our coreapi fork in every deployable installtion. Or doesnt the Task fail if the command is not there?

**Comment by achimfritz** [comment]
i dont think so (the missing the createUploadFolder Command did also not break the deployment), but i will test this

**Comment by achimfritz** [comment]
im right (TYPO3 returns not correct exit codes (only if Exception is thrown))

```
lw-af@DEV-VM:/var/www/surfcaptain/dev$ ./flow surfrunner:deploywaitingfromqueue --disable-ansi=true
Deploying 5ced2dfa-d209-11fc-bc80-266d5fa05c26 (20150603084129)
Using workflow "Simple workflow"
Stage initialize
Node gvsweb-local-test
Application #1 TYPO3\CMS\Deploy
Executing stage "initialize" (step "tasks") on "gvsweb-local-test" for application #1 TYPO3\CMS\Deploy
gvsweb-local-test (#1 TYPO3\CMS\Deploy) lightwerk.surftasks:transfer:assureconnection
node seems not to be a remote node
Task "lightwerk.surftasks:typo3:cms:assurecachedirectoryiswriteable" after "lightwerk.surftasks:transfer:assureconnection" for application #1 TYPO3\CMS\Deploy
gvsweb-local-test (#1 TYPO3\CMS\Deploy) lightwerk.surftasks:typo3:cms:assurecachedirectoryiswriteable
(localhost): "cd '/var/www/gvsweb/test/htdocs' && export TYPO3_CONTEXT='Development' && if [ -d "typo3conf/ext/coreapi" ]; then typo3/cli_dispatch.phpsh extbase cacheapi:assurecachedirectoryiswriteable; fi"
> No command could be found that matches the command identifier "cacheapi:assurecachedirectoryiswriteable".

Enter "./flow typo3/cli_dispatch.phpsh extbase help" for an overview of all available commands
or "./flow typo3/cli_dispatch.phpsh extbase help <command identifier>" for a detailed description of the corresponding command.
Stage package
Node gvsweb-local-test
Application #1 TYPO3\CMS\Deploy
Executing stage "package" (step "tasks") on "gvsweb-local-test" for application #1 TYPO3\CMS\Deploy
...
```

**Comment by ervaude** [comment]
Very good =)

**Pull request merged**
